import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { AnalyzeResponse, SkinResult } from '../types';

export const generateAndSharePDF = async (data: any, imageUri?: string) => {
  const safeData = data as any;
  const date = new Date().toLocaleDateString();
  
  const predictedClass = safeData?.predictedClass || safeData?.predicted_class || "Unknown";
  const confidence = Math.round((safeData?.confidence ?? 0) * 100);
  const riskLevel = safeData?.riskLevel || safeData?.risk_level || "Unknown";
  const suggestions = safeData?.suggestions || safeData?.rule_based_suggestions || [];
  
  const getRiskColor = (level: string) => {
    switch (level.toLowerCase()) {
      case 'low': return '#10B981';
      case 'moderate': return '#F59E0B';
      case 'high': return '#EF4444';
      case 'very high': return '#7F1D1D';
      default: return '#6B7280';
    }
  };

  const riskColor = getRiskColor(riskLevel);

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
        <style>
          body { font-family: 'Helvetica', sans-serif; color: #333; padding: 20px; line-height: 1.6; }
          .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #6366F1; padding-bottom: 20px; }
          .logo { font-size: 24px; font-weight: bold; color: #6366F1; margin-bottom: 5px; }
          .subtitle { font-size: 14px; color: #666; }
          .section { margin-bottom: 25px; background: #f9fafb; padding: 15px; border-radius: 8px; }
          .section-title { font-size: 18px; font-weight: bold; color: #111827; margin-bottom: 10px; border-left: 4px solid #6366F1; padding-left: 10px; }
          .row { display: flex; justify-content: space-between; margin-bottom: 8px; }
          .label { font-weight: 600; color: #555; }
          .value { font-weight: bold; }
          .risk-badge { display: inline-block; padding: 4px 12px; border-radius: 12px; color: white; font-weight: bold; font-size: 14px; }
          .image-container { text-align: center; margin: 20px 0; }
          .skin-image { max-width: 100%; height: auto; border-radius: 8px; max-height: 300px; object-fit: cover; }
          .suggestion-item { margin-bottom: 5px; padding-left: 20px; position: relative; }
          .suggestion-item:before { content: "•"; position: absolute; left: 0; color: #6366F1; font-weight: bold; }
          .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 20px; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="logo">GlowScan Analysis Report</div>
          <div class="subtitle">Date: ${date}</div>
        </div>

        <div class="section">
          <div class="section-title">Analysis Summary</div>
          <div class="row">
            <span class="label">Skin Type:</span>
            <span class="value" style="text-transform: capitalize;">${predictedClass}</span>
          </div>
          <div class="row">
            <span class="label">AI Confidence:</span>
            <span class="value">${confidence}%</span>
          </div>
          <div class="row" style="align-items: center;">
            <span class="label">Risk Level:</span>
            <span class="risk-badge" style="background-color: ${riskColor};">${riskLevel}</span>
          </div>
        </div>

        ${imageUri ? `
          <div class="image-container">
            <img src="${imageUri}" class="skin-image" />
          </div>
        ` : ''}

        <div class="section">
          <div class="section-title">Recommendations</div>
          ${suggestions.map((s: string) => `<div class="suggestion-item">${s}</div>`).join('')}
        </div>

        <div class="section">
          <div class="section-title">Disclaimer</div>
          <p style="font-size: 12px; color: #666;">
            This report is generated by AI for informational purposes only. It is not a medical diagnosis. 
            Please consult a certified dermatologist for professional medical advice.
          </p>
        </div>

        <div class="footer">
          Generated by GlowScan App
        </div>
      </body>
    </html>
  `;

  try {
    const { uri } = await Print.printToFileAsync({ html });
    await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
  } catch (error) {
    console.error('Error generating PDF:', error);
  }
};
